# Generated by Django 5.2.4 on 2025-08-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_managers_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('member', 'Member'), ('secretary', 'Secretary'), ('worker', 'Worker'), ('admin', 'Admin')], max_length=20, null=True),
        ),
    ]
