# Generated by Django 5.1.7 on 2025-08-05 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_issue_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues.issuecategory'),
        ),
    ]
